// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDisplayMode(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyDisplayMode'](arg1, arg2, arg3);
}

export function ChangePin(arg1, arg2) {
  return window['go']['main']['App']['ChangePin'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CheckinAttendance() {
  return window['go']['main']['App']['CheckinAttendance']();
}

export function ConfirmDisplayMode() {
  return window['go']['main']['App']['ConfirmDisplayMode']();
}

export function CreateRoom(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRoom'](arg1, arg2, arg3);
}

export function GetAttendanceStatus() {
  return window['go']['main']['App']['GetAttendanceStatus']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetDisplayInfo() {
  return window['go']['main']['App']['GetDisplayInfo']();
}

export function GetFeatureFlags() {
  return window['go']['main']['App']['GetFeatureFlags']();
}

export function GetBootTime() {
  return window['go']['main']['App']['GetBootTime']();
}

export function GetHardware() {
  return window['go']['main']['App']['GetHardware']();
}

export function GetMachineCode() {
  return window['go']['main']['App']['GetMachineCode']();
}

export function GetMyOrders() {
  return window['go']['main']['App']['GetMyOrders']();
}

export function GetMemberInfo() {
  return window['go']['main']['App']['GetMemberInfo']();
}

export function GetMenu(arg1) {
  return window['go']['main']['App']['GetMenu'](arg1);
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetRoomMessages(arg1) {
  return window['go']['main']['App']['GetRoomMessages'](arg1);
}

export function GetRooms() {
  return window['go']['main']['App']['GetRooms']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function GetTopupPresets() {
  return window['go']['main']['App']['GetTopupPresets']();
}

export function GetUnreadNotificationCount() {
  return window['go']['main']['App']['GetUnreadNotificationCount']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowMode() {
  return window['go']['main']['App']['GetWindowMode']();
}

export function HasCachedStaff() {
  return window['go']['main']['App']['HasCachedStaff']();
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function HidePanel() {
  return window['go']['main']['App']['HidePanel']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MarkAllNotificationsRead() {
  return window['go']['main']['App']['MarkAllNotificationsRead']();
}

export function MarkMessageDelivered(arg1) {
  return window['go']['main']['App']['MarkMessageDelivered'](arg1);
}

export function MarkMessageRead(arg1) {
  return window['go']['main']['App']['MarkMessageRead'](arg1);
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['App']['MarkNotificationRead'](arg1);
}

export function MarkRoomMessagesRead(arg1) {
  return window['go']['main']['App']['MarkRoomMessagesRead'](arg1);
}

export function MinimiseDock() {
  return window['go']['main']['App']['MinimiseDock']();
}

export function OpenWindow(arg1) {
  return window['go']['main']['App']['OpenWindow'](arg1);
}

export function PlaceOrder(arg1) {
  return window['go']['main']['App']['PlaceOrder'](arg1);
}

export function RequestTopup(arg1) {
  return window['go']['main']['App']['RequestTopup'](arg1);
}

export function ResetDisplayAndMouse() {
  return window['go']['main']['App']['ResetDisplayAndMouse']();
}

export function RestoreSession(arg1) {
  return window['go']['main']['App']['RestoreSession'](arg1);
}

export function RevertDisplayMode() {
  return window['go']['main']['App']['RevertDisplayMode']();
}

export function SendRoomMessage(arg1, arg2) {
  return window['go']['main']['App']['SendRoomMessage'](arg1, arg2);
}

export function SendScreenshotMessage(arg1, arg2) {
  return window['go']['main']['App']['SendScreenshotMessage'](arg1, arg2);
}

export function SetLoggedIn(arg1) {
  return window['go']['main']['App']['SetLoggedIn'](arg1);
}

export function SetMousePrecision(arg1) {
  return window['go']['main']['App']['SetMousePrecision'](arg1);
}

export function SetMouseSpeed(arg1) {
  return window['go']['main']['App']['SetMouseSpeed'](arg1);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function SubmitFeedback(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitFeedback'](arg1, arg2, arg3);
}

export function TakeScreenshot() {
  return window['go']['main']['App']['TakeScreenshot']();
}
