// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockApp(arg1) {
  return window['go']['main']['App']['BlockApp'](arg1);
}

export function ChangePin(arg1, arg2) {
  return window['go']['main']['App']['ChangePin'](arg1, arg2);
}

export function CreateRoom(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRoom'](arg1, arg2, arg3);
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetHardware() {
  return window['go']['main']['App']['GetHardware']();
}

export function GetMachineCode() {
  return window['go']['main']['App']['GetMachineCode']();
}

export function GetMemberInfo() {
  return window['go']['main']['App']['GetMemberInfo']();
}

export function GetMenu(arg1) {
  return window['go']['main']['App']['GetMenu'](arg1);
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetRoomMessages(arg1) {
  return window['go']['main']['App']['GetRoomMessages'](arg1);
}

export function GetRooms() {
  return window['go']['main']['App']['GetRooms']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function GetTopupPresets() {
  return window['go']['main']['App']['GetTopupPresets']();
}

export function GetUnreadNotificationCount() {
  return window['go']['main']['App']['GetUnreadNotificationCount']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function LoginAdmin(arg1, arg2) {
  return window['go']['main']['App']['LoginAdmin'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MarkAllNotificationsRead() {
  return window['go']['main']['App']['MarkAllNotificationsRead']();
}

export function MarkMessageDelivered(arg1) {
  return window['go']['main']['App']['MarkMessageDelivered'](arg1);
}

export function MarkMessageRead(arg1) {
  return window['go']['main']['App']['MarkMessageRead'](arg1);
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['App']['MarkNotificationRead'](arg1);
}

export function MarkRoomMessagesRead(arg1) {
  return window['go']['main']['App']['MarkRoomMessagesRead'](arg1);
}

export function PlaceOrder(arg1) {
  return window['go']['main']['App']['PlaceOrder'](arg1);
}

export function RequestTopup(arg1) {
  return window['go']['main']['App']['RequestTopup'](arg1);
}

export function RestartMachine() {
  return window['go']['main']['App']['RestartMachine']();
}

export function RestoreSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RestoreSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SendRoomMessage(arg1, arg2) {
  return window['go']['main']['App']['SendRoomMessage'](arg1, arg2);
}

export function SendScreenshotMessage(arg1, arg2) {
  return window['go']['main']['App']['SendScreenshotMessage'](arg1, arg2);
}

export function SetMachineCode(arg1) {
  return window['go']['main']['App']['SetMachineCode'](arg1);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function ShutdownMachine() {
  return window['go']['main']['App']['ShutdownMachine']();
}

export function TakeScreenshot() {
  return window['go']['main']['App']['TakeScreenshot']();
}

export function UnblockApp(arg1) {
  return window['go']['main']['App']['UnblockApp'](arg1);
}
