// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function BlockApp(arg1:string):Promise<void>;

export function ChangePin(arg1:string,arg2:string):Promise<string>;

export function CheckUpdate():Promise<string>;

export function CheckinAttendance():Promise<string>;

export function CreateRoom(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadUpdate():Promise<string>;

export function ExecuteCommand(arg1:string):Promise<string>;

export function GetAttendanceStatus():Promise<string>;

export function GetCategories():Promise<string>;

export function GetFeatureFlags():Promise<string>;

export function GetHardware():Promise<string>;

export function GetMachineCode():Promise<string>;

export function GetMemberInfo():Promise<string>;

export function GetMenu(arg1:string):Promise<string>;

export function GetNotifications():Promise<string>;

export function GetRoomMessages(arg1:string):Promise<string>;

export function GetRooms():Promise<string>;

export function GetServerURL():Promise<string>;

export function GetSession():Promise<string>;

export function GetTopupPresets():Promise<string>;

export function GetUnreadNotificationCount():Promise<string>;

export function GetUserInfo():Promise<string>;

export function GetVersion():Promise<string>;

export function GetWindowMode():Promise<string>;

export function HasBuiltinAdmin():Promise<boolean>;

export function HasCachedStaff():Promise<boolean>;

export function HasMaintenancePin():Promise<boolean>;

export function IsLocked():Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function LockScreen(arg1:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<void>;

export function MarkAllNotificationsRead():Promise<string>;

export function MarkMessageDelivered(arg1:string):Promise<string>;

export function MarkMessageRead(arg1:string):Promise<string>;

export function MarkNotificationRead(arg1:string):Promise<string>;

export function MarkRoomMessagesRead(arg1:string):Promise<string>;

export function OpenWindow(arg1:string):Promise<void>;

export function PlaceOrder(arg1:string):Promise<string>;

export function RequestTopup(arg1:number):Promise<string>;

export function RestartMachine():Promise<string>;

export function RestoreSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SendRoomMessage(arg1:string,arg2:string):Promise<string>;

export function SendScreenshotMessage(arg1:string,arg2:string):Promise<string>;

export function SetLoggedIn(arg1:boolean):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function ShutdownMachine():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function SubmitFeedback(arg1:number,arg2:string,arg3:string):Promise<string>;

export function TakeScreenshot():Promise<string>;

export function UnblockApp(arg1:string):Promise<void>;

export function UnlockMaintenance(arg1:string):Promise<void>;

export function UnlockScreen():Promise<void>;
