// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockApp(arg1:string):Promise<void>;

export function ChangePin(arg1:string,arg2:string):Promise<string>;

export function CreateConversation(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteCommand(arg1:string):Promise<string>;

export function GetCategories():Promise<string>;

export function GetChatMessages(arg1:string):Promise<string>;

export function GetConversations():Promise<string>;

export function GetHardware():Promise<string>;

export function GetMachineCode():Promise<string>;

export function GetMemberInfo():Promise<string>;

export function GetMenu(arg1:string):Promise<string>;

export function GetNotifications():Promise<string>;

export function GetServerURL():Promise<string>;

export function GetSession():Promise<string>;

export function GetTopupPresets():Promise<string>;

export function GetUnreadNotificationCount():Promise<string>;

export function GetUserInfo():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function LoginAdmin(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<void>;

export function MarkAllNotificationsRead():Promise<string>;

export function MarkConversationMessagesRead(arg1:string):Promise<string>;

export function MarkMessageDelivered(arg1:string):Promise<string>;

export function MarkMessageRead(arg1:string):Promise<string>;

export function MarkNotificationRead(arg1:string):Promise<string>;

export function PlaceOrder(arg1:string):Promise<string>;

export function RequestTopup(arg1:number):Promise<string>;

export function RestartMachine():Promise<string>;

export function RestoreSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function SendChatMessage(arg1:string,arg2:string):Promise<string>;

export function SendScreenshotMessage(arg1:string,arg2:string):Promise<string>;

export function SetMachineCode(arg1:string):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<string>;

export function ShutdownMachine():Promise<string>;

export function TakeScreenshot():Promise<string>;

export function UnblockApp(arg1:string):Promise<void>;
