/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  alova_request: () => import("@/views/alova/request/index.vue"),
  alova_scenes: () => import("@/views/alova/scenes/index.vue"),
  alova_user: () => import("@/views/alova/user/index.vue"),
  "function_hide-child_one": () => import("@/views/function/hide-child/one/index.vue"),
  "function_hide-child_three": () => import("@/views/function/hide-child/three/index.vue"),
  "function_hide-child_two": () => import("@/views/function/hide-child/two/index.vue"),
  "function_multi-tab": () => import("@/views/function/multi-tab/index.vue"),
  function_request: () => import("@/views/function/request/index.vue"),
  "function_super-page": () => import("@/views/function/super-page/index.vue"),
  function_tab: () => import("@/views/function/tab/index.vue"),
  "function_toggle-auth": () => import("@/views/function/toggle-auth/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "multi-menu_first_child": () => import("@/views/multi-menu/first_child/index.vue"),
  "multi-menu_second_child_home": () => import("@/views/multi-menu/second_child_home/index.vue"),
  plugin_barcode: () => import("@/views/plugin/barcode/index.vue"),
  plugin_charts_antv: () => import("@/views/plugin/charts/antv/index.vue"),
  plugin_charts_echarts: () => import("@/views/plugin/charts/echarts/index.vue"),
  plugin_charts_vchart: () => import("@/views/plugin/charts/vchart/index.vue"),
  plugin_copy: () => import("@/views/plugin/copy/index.vue"),
  plugin_editor_markdown: () => import("@/views/plugin/editor/markdown/index.vue"),
  plugin_editor_quill: () => import("@/views/plugin/editor/quill/index.vue"),
  plugin_excel: () => import("@/views/plugin/excel/index.vue"),
  plugin_gantt_dhtmlx: () => import("@/views/plugin/gantt/dhtmlx/index.vue"),
  plugin_gantt_vtable: () => import("@/views/plugin/gantt/vtable/index.vue"),
  plugin_icon: () => import("@/views/plugin/icon/index.vue"),
  plugin_map: () => import("@/views/plugin/map/index.vue"),
  plugin_pdf: () => import("@/views/plugin/pdf/index.vue"),
  plugin_pinyin: () => import("@/views/plugin/pinyin/index.vue"),
  plugin_print: () => import("@/views/plugin/print/index.vue"),
  plugin_swiper: () => import("@/views/plugin/swiper/index.vue"),
  plugin_tables_vtable: () => import("@/views/plugin/tables/vtable/index.vue"),
  plugin_typeit: () => import("@/views/plugin/typeit/index.vue"),
  plugin_video: () => import("@/views/plugin/video/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  "system_user-detail": () => import("@/views/system/user-detail/[id].vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  vnet_audit: () => import("@/views/vnet/audit/index.vue"),
  vnet_backups: () => import("@/views/vnet/backups/index.vue"),
  vnet_bookings: () => import("@/views/vnet/bookings/index.vue"),
  vnet_categories: () => import("@/views/vnet/categories/index.vue"),
  vnet_combos: () => import("@/views/vnet/combos/index.vue"),
  vnet_dashboard: () => import("@/views/vnet/dashboard/index.vue"),
  "vnet_machine-groups": () => import("@/views/vnet/machine-groups/index.vue"),
  vnet_machines: () => import("@/views/vnet/machines/index.vue"),
  "vnet_member-groups": () => import("@/views/vnet/member-groups/index.vue"),
  vnet_members: () => import("@/views/vnet/members/index.vue"),
  vnet_orders: () => import("@/views/vnet/orders/index.vue"),
  vnet_products: () => import("@/views/vnet/products/index.vue"),
  vnet_promotions: () => import("@/views/vnet/promotions/index.vue"),
  vnet_reports: () => import("@/views/vnet/reports/index.vue"),
  vnet_sessions: () => import("@/views/vnet/sessions/index.vue"),
  vnet_settings: () => import("@/views/vnet/settings/index.vue"),
  vnet_shifts: () => import("@/views/vnet/shifts/index.vue"),
  "vnet_stock-transactions": () => import("@/views/vnet/stock-transactions/index.vue"),
  vnet_suppliers: () => import("@/views/vnet/suppliers/index.vue"),
  vnet_transactions: () => import("@/views/vnet/transactions/index.vue"),
  vnet_warehouses: () => import("@/views/vnet/warehouses/index.vue"),
};
