/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10
    }
  },
  {
    name: 'alova',
    path: '/alova',
    component: 'layout.base',
    meta: {
      title: 'alova',
      i18nKey: 'route.alova',
      icon: 'carbon:http',
      order: 7
    },
    children: [
      {
        name: 'alova_request',
        path: '/alova/request',
        component: 'view.alova_request',
        meta: {
          title: 'alova_request',
          i18nKey: 'route.alova_request',
          order: 1
        }
      },
      {
        name: 'alova_scenes',
        path: '/alova/scenes',
        component: 'view.alova_scenes',
        meta: {
          title: 'alova_scenes',
          i18nKey: 'route.alova_scenes',
          icon: 'cbi:scene-dynamic',
          order: 3
        }
      },
      {
        name: 'alova_user',
        path: '/alova/user',
        component: 'view.alova_user',
        meta: {
          title: 'alova_user',
          i18nKey: 'route.alova_user',
          icon: 'carbon:user-multiple',
          order: 2
        }
      }
    ]
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'icon-park-outline:all-application',
      order: 6
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child',
          icon: 'material-symbols:filter-list-off',
          order: 2
        },
        redirect: '/function/hide-child/one',
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one',
              icon: 'material-symbols:filter-list-off',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab',
          icon: 'ic:round-tab',
          multiTab: true,
          hideInMenu: true,
          activeMenu: 'function_tab'
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request',
          icon: 'carbon:network-overlay',
          order: 3
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page',
          icon: 'ic:round-supervisor-account',
          order: 5,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab',
          icon: 'ic:round-tab',
          order: 1
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth',
          icon: 'ic:round-construction',
          order: 4
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu',
      icon: 'carbon:stack',
      order: 8
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first',
          icon: 'carbon:folder',
          order: 1
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child',
              icon: 'carbon:document'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second',
          icon: 'carbon:folder',
          order: 2
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child',
              icon: 'carbon:document'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home',
                  icon: 'carbon:home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'plugin',
    path: '/plugin',
    component: 'layout.base',
    meta: {
      title: '插件示例',
      i18nKey: 'route.plugin',
      order: 7,
      icon: 'clarity:plugin-line'
    },
    children: [
      {
        name: 'plugin_barcode',
        path: '/plugin/barcode',
        component: 'view.plugin_barcode',
        meta: {
          title: 'plugin_barcode',
          i18nKey: 'route.plugin_barcode',
          icon: 'ic:round-barcode'
        }
      },
      {
        name: 'plugin_charts',
        path: '/plugin/charts',
        meta: {
          title: 'plugin_charts',
          i18nKey: 'route.plugin_charts',
          icon: 'mdi:chart-areaspline'
        },
        children: [
          {
            name: 'plugin_charts_antv',
            path: '/plugin/charts/antv',
            component: 'view.plugin_charts_antv',
            meta: {
              title: 'plugin_charts_antv',
              i18nKey: 'route.plugin_charts_antv',
              icon: 'hugeicons:flow-square'
            }
          },
          {
            name: 'plugin_charts_echarts',
            path: '/plugin/charts/echarts',
            component: 'view.plugin_charts_echarts',
            meta: {
              title: 'plugin_charts_echarts',
              i18nKey: 'route.plugin_charts_echarts',
              icon: 'simple-icons:apacheecharts'
            }
          },
          {
            name: 'plugin_charts_vchart',
            path: '/plugin/charts/vchart',
            component: 'view.plugin_charts_vchart',
            meta: {
              title: 'plugin_charts_vchart',
              i18nKey: 'route.plugin_charts_vchart',
              localIcon: 'visactor'
            }
          }
        ]
      },
      {
        name: 'plugin_copy',
        path: '/plugin/copy',
        component: 'view.plugin_copy',
        meta: {
          title: 'plugin_copy',
          i18nKey: 'route.plugin_copy',
          icon: 'mdi:clipboard-outline'
        }
      },
      {
        name: 'plugin_editor',
        path: '/plugin/editor',
        meta: {
          title: 'plugin_editor',
          i18nKey: 'route.plugin_editor',
          icon: 'icon-park-outline:editor'
        },
        children: [
          {
            name: 'plugin_editor_markdown',
            path: '/plugin/editor/markdown',
            component: 'view.plugin_editor_markdown',
            meta: {
              title: 'plugin_editor_markdown',
              i18nKey: 'route.plugin_editor_markdown',
              icon: 'ri:markdown-line'
            }
          },
          {
            name: 'plugin_editor_quill',
            path: '/plugin/editor/quill',
            component: 'view.plugin_editor_quill',
            meta: {
              title: 'plugin_editor_quill',
              i18nKey: 'route.plugin_editor_quill',
              icon: 'mdi:file-document-edit-outline'
            }
          }
        ]
      },
      {
        name: 'plugin_excel',
        path: '/plugin/excel',
        component: 'view.plugin_excel',
        meta: {
          title: 'plugin_excel',
          i18nKey: 'route.plugin_excel',
          icon: 'ri:file-excel-2-line',
          keepAlive: true
        }
      },
      {
        name: 'plugin_gantt',
        path: '/plugin/gantt',
        meta: {
          title: 'plugin_gantt',
          i18nKey: 'route.plugin_gantt',
          icon: 'ant-design:bar-chart-outlined'
        },
        children: [
          {
            name: 'plugin_gantt_dhtmlx',
            path: '/plugin/gantt/dhtmlx',
            component: 'view.plugin_gantt_dhtmlx',
            meta: {
              title: 'plugin_gantt_dhtmlx',
              i18nKey: 'route.plugin_gantt_dhtmlx',
              icon: 'gridicons:posts'
            }
          },
          {
            name: 'plugin_gantt_vtable',
            path: '/plugin/gantt/vtable',
            component: 'view.plugin_gantt_vtable',
            meta: {
              title: 'plugin_gantt_vtable',
              i18nKey: 'route.plugin_gantt_vtable',
              localIcon: 'visactor'
            }
          }
        ]
      },
      {
        name: 'plugin_icon',
        path: '/plugin/icon',
        component: 'view.plugin_icon',
        meta: {
          title: 'plugin_icon',
          i18nKey: 'route.plugin_icon',
          localIcon: 'custom-icon'
        }
      },
      {
        name: 'plugin_map',
        path: '/plugin/map',
        component: 'view.plugin_map',
        meta: {
          title: 'plugin_map',
          i18nKey: 'route.plugin_map',
          icon: 'mdi:map'
        }
      },
      {
        name: 'plugin_pdf',
        path: '/plugin/pdf',
        component: 'view.plugin_pdf',
        meta: {
          title: 'plugin_pdf',
          i18nKey: 'route.plugin_pdf',
          icon: 'uiw:file-pdf'
        }
      },
      {
        name: 'plugin_pinyin',
        path: '/plugin/pinyin',
        component: 'view.plugin_pinyin',
        meta: {
          title: 'plugin_pinyin',
          i18nKey: 'route.plugin_pinyin',
          icon: 'entypo-social:google-hangouts'
        }
      },
      {
        name: 'plugin_print',
        path: '/plugin/print',
        component: 'view.plugin_print',
        meta: {
          title: 'plugin_print',
          i18nKey: 'route.plugin_print',
          icon: 'mdi:printer'
        }
      },
      {
        name: 'plugin_swiper',
        path: '/plugin/swiper',
        component: 'view.plugin_swiper',
        meta: {
          title: 'plugin_swiper',
          i18nKey: 'route.plugin_swiper',
          icon: 'simple-icons:swiper'
        }
      },
      {
        name: 'plugin_tables',
        path: '/plugin/tables',
        meta: {
          title: 'plugin_tables',
          i18nKey: 'route.plugin_tables',
          icon: 'icon-park-outline:table'
        },
        children: [
          {
            name: 'plugin_tables_vtable',
            path: '/plugin/tables/vtable',
            component: 'view.plugin_tables_vtable',
            meta: {
              title: 'plugin_tables_vtable',
              i18nKey: 'route.plugin_tables_vtable',
              localIcon: 'visactor'
            }
          }
        ]
      },
      {
        name: 'plugin_typeit',
        path: '/plugin/typeit',
        component: 'view.plugin_typeit',
        meta: {
          title: 'plugin_typeit',
          i18nKey: 'route.plugin_typeit',
          icon: 'mdi:typewriter'
        }
      },
      {
        name: 'plugin_video',
        path: '/plugin/video',
        component: 'view.plugin_video',
        meta: {
          title: 'plugin_video',
          i18nKey: 'route.plugin_video',
          icon: 'mdi:video'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'carbon:security'
    },
    children: [
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          icon: 'carbon:category'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role',
          icon: 'carbon:user-role'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'carbon:user-avatar'
        }
      },
      {
        name: 'system_user-detail',
        path: '/system/user-detail/:id',
        component: 'view.system_user-detail',
        meta: {
          title: 'system_user-detail',
          i18nKey: 'route.system_user-detail'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  },
  {
    name: 'vnet',
    path: '/vnet',
    component: 'layout.base',
    meta: {
      title: 'vnet',
      icon: 'ant-design:appstore-outlined',
      order: 1,
      i18nKey: 'route.vnet'
    },
    children: [
      {
        name: 'vnet_audit',
        path: '/vnet/audit',
        component: 'view.vnet_audit',
        meta: {
          title: 'vnet_audit',
          i18nKey: 'route.vnet_audit'
        }
      },
      {
        name: 'vnet_backups',
        path: '/vnet/backups',
        component: 'view.vnet_backups',
        meta: {
          title: 'vnet_backups',
          i18nKey: 'route.vnet_backups'
        }
      },
      {
        name: 'vnet_bookings',
        path: '/vnet/bookings',
        component: 'view.vnet_bookings',
        meta: {
          title: 'vnet_bookings',
          i18nKey: 'route.vnet_bookings'
        }
      },
      {
        name: 'vnet_categories',
        path: '/vnet/categories',
        component: 'view.vnet_categories',
        meta: {
          title: 'vnet_categories',
          i18nKey: 'route.vnet_categories'
        }
      },
      {
        name: 'vnet_combos',
        path: '/vnet/combos',
        component: 'view.vnet_combos',
        meta: {
          title: 'vnet_combos',
          i18nKey: 'route.vnet_combos'
        }
      },
      {
        name: 'vnet_dashboard',
        path: '/vnet/dashboard',
        component: 'view.vnet_dashboard',
        meta: {
          title: 'vnet_dashboard',
          i18nKey: 'route.vnet_dashboard'
        }
      },
      {
        name: 'vnet_machine-groups',
        path: '/vnet/machine-groups',
        component: 'view.vnet_machine-groups',
        meta: {
          title: 'vnet_machine-groups',
          i18nKey: 'route.vnet_machine-groups'
        }
      },
      {
        name: 'vnet_machines',
        path: '/vnet/machines',
        component: 'view.vnet_machines',
        meta: {
          title: 'vnet_machines',
          i18nKey: 'route.vnet_machines'
        }
      },
      {
        name: 'vnet_member-groups',
        path: '/vnet/member-groups',
        component: 'view.vnet_member-groups',
        meta: {
          title: 'vnet_member-groups',
          i18nKey: 'route.vnet_member-groups'
        }
      },
      {
        name: 'vnet_members',
        path: '/vnet/members',
        component: 'view.vnet_members',
        meta: {
          title: 'vnet_members',
          i18nKey: 'route.vnet_members'
        }
      },
      {
        name: 'vnet_orders',
        path: '/vnet/orders',
        component: 'view.vnet_orders',
        meta: {
          title: 'vnet_orders',
          i18nKey: 'route.vnet_orders'
        }
      },
      {
        name: 'vnet_products',
        path: '/vnet/products',
        component: 'view.vnet_products',
        meta: {
          title: 'vnet_products',
          i18nKey: 'route.vnet_products'
        }
      },
      {
        name: 'vnet_promotions',
        path: '/vnet/promotions',
        component: 'view.vnet_promotions',
        meta: {
          title: 'vnet_promotions',
          i18nKey: 'route.vnet_promotions'
        }
      },
      {
        name: 'vnet_reports',
        path: '/vnet/reports',
        component: 'view.vnet_reports',
        meta: {
          title: 'vnet_reports',
          i18nKey: 'route.vnet_reports'
        }
      },
      {
        name: 'vnet_sessions',
        path: '/vnet/sessions',
        component: 'view.vnet_sessions',
        meta: {
          title: 'vnet_sessions',
          i18nKey: 'route.vnet_sessions'
        }
      },
      {
        name: 'vnet_settings',
        path: '/vnet/settings',
        component: 'view.vnet_settings',
        meta: {
          title: 'vnet_settings',
          i18nKey: 'route.vnet_settings'
        }
      },
      {
        name: 'vnet_shifts',
        path: '/vnet/shifts',
        component: 'view.vnet_shifts',
        meta: {
          title: 'vnet_shifts',
          i18nKey: 'route.vnet_shifts'
        }
      },
      {
        name: 'vnet_stock-transactions',
        path: '/vnet/stock-transactions',
        component: 'view.vnet_stock-transactions',
        meta: {
          title: 'vnet_stock-transactions',
          i18nKey: 'route.vnet_stock-transactions'
        }
      },
      {
        name: 'vnet_suppliers',
        path: '/vnet/suppliers',
        component: 'view.vnet_suppliers',
        meta: {
          title: 'vnet_suppliers',
          i18nKey: 'route.vnet_suppliers'
        }
      },
      {
        name: 'vnet_transactions',
        path: '/vnet/transactions',
        component: 'view.vnet_transactions',
        meta: {
          title: 'vnet_transactions',
          i18nKey: 'route.vnet_transactions'
        }
      },
      {
        name: 'vnet_warehouses',
        path: '/vnet/warehouses',
        component: 'view.vnet_warehouses',
        meta: {
          title: 'vnet_warehouses',
          i18nKey: 'route.vnet_warehouses'
        }
      }
    ]
  }
];
